version: '3.8'

services:
  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: IT2017petro
      DB_NAME: impuestos
    container_name: php_apache_imp
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always
    # command: /bin/sh -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"

  db:
    image: mariadb:10.4.21
    container_name: mysql_db_imp
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: IT2017petro
      MYSQL_DATABASE: impuestos
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: my_phpmyadmin_imp
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: IT2017petro
    ports:
      - "8082:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:




