name: Deploy to VPS

on:
  push:
    branches:
      - master  # Cambiar a 'main' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/pagospilar
            git pull origin master
            # Recargar solo los contenedores si docker-compose cambió (opcional pero seguro)
            # docker compose up -d
